import type { NextPage } from 'next';
import Head from 'next/head';
import HeroSection from '../components/HeroSection';
import OfferSection from '../components/OfferSection';
import TeamSection from '../components/TeamSection';
import { easeInOut, motion as m } from 'framer-motion';

const Home: NextPage = () => {
  return (
    <m.div
      initial={{ opacity: 0 }}
      exit={{ opacity: 1 }}
      animate={{ opacity: 1 }}
      transition={{ duration: 0.86, easings: easeInOut }}
    >
      <Head>
        <title>Frontendinit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroSection />
      <OfferSection />
      {/* <TeamSection /> */}
    </m.div>
  );
};

export default Home;
