import type { NextPage } from 'next';
import Head from 'next/head';
import HeroSection from '../components/HeroSection';
import OfferSection from '../components/OfferSection';
import TeamSection from '../components/TeamSection';

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Frontendinit</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <HeroSection />
      <OfferSection />
      {/* <TeamSection /> */}
    </div>
  );
};

export default Home;
